# Generated by Django 4.2.2 on 2023-06-24 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("author", models.CharField(max_length=30)),
                ("genre", models.CharField(max_length=30)),
                ("read_date", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
